; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	test_function:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+45
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010d01H
	DD	0620dH
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
expr$ = 32
byte$ = 33
argc$ = 64
argv$ = 72
main	PROC
; File c:\dev\emble\test_func.c
; Line 4
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 5
	mov	BYTE PTR byte$[rsp], 17
; Line 6
	mov	BYTE PTR expr$[rsp], 16
; Line 7
	movzx	edx, BYTE PTR expr$[rsp]
	movzx	ecx, BYTE PTR byte$[rsp]
	call	test_function
; Line 8
	xor	eax, eax
; Line 9
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
