/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 155
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_export = 1,
  anon_sym_import = 2,
  anon_sym_COMMA = 3,
  anon_sym_from = 4,
  anon_sym_struct = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON = 8,
  anon_sym_interface = 9,
  anon_sym_impl = 10,
  anon_sym_on = 11,
  anon_sym_func = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_self = 15,
  anon_sym_EQ = 16,
  anon_sym_let = 17,
  anon_sym_const = 18,
  anon_sym_if = 19,
  anon_sym_while = 20,
  anon_sym_for = 21,
  anon_sym_in = 22,
  anon_sym_return = 23,
  anon_sym_PLUS_EQ = 24,
  anon_sym_DASH_EQ = 25,
  anon_sym_SLASH_EQ = 26,
  anon_sym_STAR_EQ = 27,
  anon_sym_true = 28,
  anon_sym_false = 29,
  anon_sym_PLUS = 30,
  anon_sym_DASH = 31,
  anon_sym_STAR = 32,
  anon_sym_SLASH = 33,
  sym_identifier = 34,
  sym_integer = 35,
  sym_float = 36,
  sym_source_file = 37,
  sym_export_definition = 38,
  sym_definition = 39,
  sym_import_definition = 40,
  sym_import_all = 41,
  sym_import_from = 42,
  sym_struct = 43,
  sym_struct_field = 44,
  sym_interface = 45,
  sym_impl = 46,
  sym_function = 47,
  sym_function_decl = 48,
  sym_parameter_list = 49,
  sym_self_function = 50,
  sym_self_function_decl = 51,
  sym_self_parameter_list = 52,
  sym_statement = 53,
  sym_block = 54,
  sym_variable = 55,
  sym_variable_specifier = 56,
  sym_if_stmt = 57,
  sym_while_stmt = 58,
  sym_for_stmt = 59,
  sym_return_stmt = 60,
  sym_assignment_stmt = 61,
  sym_assignment_op = 62,
  sym_expression = 63,
  sym_boolean_constant = 64,
  sym_binary_op = 65,
  sym_op = 66,
  aux_sym_source_file_repeat1 = 67,
  aux_sym_import_from_repeat1 = 68,
  aux_sym_struct_repeat1 = 69,
  aux_sym_interface_repeat1 = 70,
  aux_sym_impl_repeat1 = 71,
  aux_sym_parameter_list_repeat1 = 72,
  aux_sym_block_repeat1 = 73,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_export] = "export",
  [anon_sym_import] = "import",
  [anon_sym_COMMA] = ",",
  [anon_sym_from] = "from",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_interface] = "interface",
  [anon_sym_impl] = "impl",
  [anon_sym_on] = "on",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_self] = "self",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_const] = "const",
  [anon_sym_if] = "if",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_return] = "return",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_source_file] = "source_file",
  [sym_export_definition] = "export_definition",
  [sym_definition] = "definition",
  [sym_import_definition] = "import_definition",
  [sym_import_all] = "import_all",
  [sym_import_from] = "import_from",
  [sym_struct] = "struct",
  [sym_struct_field] = "struct_field",
  [sym_interface] = "interface",
  [sym_impl] = "impl",
  [sym_function] = "function",
  [sym_function_decl] = "function_decl",
  [sym_parameter_list] = "parameter_list",
  [sym_self_function] = "self_function",
  [sym_self_function_decl] = "self_function_decl",
  [sym_self_parameter_list] = "self_parameter_list",
  [sym_statement] = "statement",
  [sym_block] = "block",
  [sym_variable] = "variable",
  [sym_variable_specifier] = "variable_specifier",
  [sym_if_stmt] = "if_stmt",
  [sym_while_stmt] = "while_stmt",
  [sym_for_stmt] = "for_stmt",
  [sym_return_stmt] = "return_stmt",
  [sym_assignment_stmt] = "assignment_stmt",
  [sym_assignment_op] = "assignment_op",
  [sym_expression] = "expression",
  [sym_boolean_constant] = "boolean_constant",
  [sym_binary_op] = "binary_op",
  [sym_op] = "op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_from_repeat1] = "import_from_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_interface_repeat1] = "interface_repeat1",
  [aux_sym_impl_repeat1] = "impl_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_interface] = anon_sym_interface,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_self] = anon_sym_self,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_source_file] = sym_source_file,
  [sym_export_definition] = sym_export_definition,
  [sym_definition] = sym_definition,
  [sym_import_definition] = sym_import_definition,
  [sym_import_all] = sym_import_all,
  [sym_import_from] = sym_import_from,
  [sym_struct] = sym_struct,
  [sym_struct_field] = sym_struct_field,
  [sym_interface] = sym_interface,
  [sym_impl] = sym_impl,
  [sym_function] = sym_function,
  [sym_function_decl] = sym_function_decl,
  [sym_parameter_list] = sym_parameter_list,
  [sym_self_function] = sym_self_function,
  [sym_self_function_decl] = sym_self_function_decl,
  [sym_self_parameter_list] = sym_self_parameter_list,
  [sym_statement] = sym_statement,
  [sym_block] = sym_block,
  [sym_variable] = sym_variable,
  [sym_variable_specifier] = sym_variable_specifier,
  [sym_if_stmt] = sym_if_stmt,
  [sym_while_stmt] = sym_while_stmt,
  [sym_for_stmt] = sym_for_stmt,
  [sym_return_stmt] = sym_return_stmt,
  [sym_assignment_stmt] = sym_assignment_stmt,
  [sym_assignment_op] = sym_assignment_op,
  [sym_expression] = sym_expression,
  [sym_boolean_constant] = sym_boolean_constant,
  [sym_binary_op] = sym_binary_op,
  [sym_op] = sym_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_from_repeat1] = aux_sym_import_from_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_interface_repeat1] = aux_sym_interface_repeat1,
  [aux_sym_impl_repeat1] = aux_sym_impl_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_interface] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_export_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_import_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_import_all] = {
    .visible = true,
    .named = true,
  },
  [sym_import_from] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_self_function] = {
    .visible = true,
    .named = true,
  },
  [sym_self_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_self_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_if_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_while_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_for_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_return_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_op] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_from_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interface_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_impl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_interface = 1,
  field_name = 2,
  field_return_type = 3,
  field_struct = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_interface] = "interface",
  [field_name] = "name",
  [field_return_type] = "return_type",
  [field_struct] = "struct",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 4},
  [7] = {.index = 13, .length = 4},
  [8] = {.index = 17, .length = 2},
  [9] = {.index = 19, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_return_type, 3},
  [3] =
    {field_interface, 1},
    {field_struct, 3},
  [5] =
    {field_name, 0},
    {field_type, 2},
  [7] =
    {field_name, 1},
    {field_type, 3},
  [9] =
    {field_name, 1},
    {field_name, 4, .inherited = true},
    {field_type, 3},
    {field_type, 4, .inherited = true},
  [13] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
  [17] =
    {field_name, 3},
    {field_type, 5},
  [19] =
    {field_name, 3},
    {field_name, 6, .inherited = true},
    {field_type, 5},
    {field_type, 6, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 4,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 31,
  [32] = 26,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 63,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 28,
  [84] = 26,
  [85] = 66,
  [86] = 72,
  [87] = 73,
  [88] = 74,
  [89] = 89,
  [90] = 90,
  [91] = 77,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 78,
  [98] = 79,
  [99] = 99,
  [100] = 80,
  [101] = 81,
  [102] = 82,
  [103] = 103,
  [104] = 65,
  [105] = 105,
  [106] = 106,
  [107] = 76,
  [108] = 108,
  [109] = 94,
  [110] = 89,
  [111] = 95,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 116,
  [149] = 126,
  [150] = 150,
  [151] = 115,
  [152] = 131,
  [153] = 143,
  [154] = 150,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(78);
      ADVANCE_MAP(
        '(', 92,
        ')', 93,
        '*', 123,
        '+', 119,
        ',', 81,
        '-', 121,
        '.', 75,
        '/', 125,
        ':', 86,
        '=', 96,
        'c', 47,
        'e', 74,
        'f', 9,
        'i', 26,
        'l', 15,
        'o', 40,
        'r', 22,
        's', 21,
        't', 51,
        'w', 31,
        '{', 84,
        '}', 85,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(93);
      if (lookahead == 's') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(93);
      if (lookahead == '{') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '*', 122,
        '+', 118,
        '-', 120,
        '/', 124,
        'c', 45,
        'f', 46,
        'i', 29,
        'l', 20,
        'r', 23,
        'w', 32,
        '{', 84,
        '}', 85,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(75);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 't') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(113);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(110);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(112);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead == 'r') ADVANCE(44);
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(90);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(66);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(101);
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(11);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == '}') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 31:
      if (lookahead == 'h') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(88);
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(82);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 50:
      if (lookahead == 'p') ADVANCE(48);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(44);
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 71:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 72:
      if (lookahead == 'u') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 74:
      if (lookahead == 'x') ADVANCE(50);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 77:
      if (eof) ADVANCE(78);
      ADVANCE_MAP(
        '*', 5,
        '+', 6,
        ',', 81,
        '-', 7,
        '/', 8,
        '=', 96,
        'e', 74,
        'f', 53,
        'i', 39,
        's', 69,
        '}', 85,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_interface);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_self);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_self);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(110);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(113);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(112);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 77},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 77},
  [12] = {.lex_state = 77},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 77},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 77},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 77},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 77},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 77},
  [39] = {.lex_state = 77},
  [40] = {.lex_state = 77},
  [41] = {.lex_state = 77},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 77},
  [44] = {.lex_state = 77},
  [45] = {.lex_state = 77},
  [46] = {.lex_state = 77},
  [47] = {.lex_state = 77},
  [48] = {.lex_state = 77},
  [49] = {.lex_state = 77},
  [50] = {.lex_state = 30},
  [51] = {.lex_state = 77},
  [52] = {.lex_state = 30},
  [53] = {.lex_state = 77},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 30},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 30},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 30},
  [77] = {.lex_state = 30},
  [78] = {.lex_state = 30},
  [79] = {.lex_state = 30},
  [80] = {.lex_state = 30},
  [81] = {.lex_state = 30},
  [82] = {.lex_state = 30},
  [83] = {.lex_state = 30},
  [84] = {.lex_state = 30},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 2},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 2},
  [139] = {.lex_state = 2},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 2},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 2},
  [145] = {.lex_state = 2},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 2},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 2},
  [151] = {.lex_state = 2},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_self] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(142),
    [sym_export_definition] = STATE(12),
    [sym_definition] = STATE(12),
    [sym_import_definition] = STATE(43),
    [sym_import_all] = STATE(41),
    [sym_import_from] = STATE(41),
    [sym_struct] = STATE(43),
    [sym_interface] = STATE(43),
    [sym_impl] = STATE(43),
    [sym_function] = STATE(43),
    [sym_function_decl] = STATE(90),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_export] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_interface] = ACTIONS(11),
    [anon_sym_impl] = ACTIONS(13),
    [anon_sym_func] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    STATE(24), 1,
      sym_statement,
    STATE(33), 1,
      sym_op,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [47] = 12,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    STATE(25), 1,
      sym_statement,
    STATE(33), 1,
      sym_op,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [94] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [136] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [178] = 11,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(48), 1,
      anon_sym_while,
    ACTIONS(51), 1,
      anon_sym_for,
    ACTIONS(54), 1,
      anon_sym_return,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(42), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [220] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [262] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [304] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(8), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [346] = 11,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [388] = 11,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      anon_sym_export,
    ACTIONS(73), 1,
      anon_sym_import,
    ACTIONS(76), 1,
      anon_sym_struct,
    ACTIONS(79), 1,
      anon_sym_interface,
    ACTIONS(82), 1,
      anon_sym_impl,
    ACTIONS(85), 1,
      anon_sym_func,
    STATE(90), 1,
      sym_function_decl,
    STATE(41), 2,
      sym_import_all,
      sym_import_from,
    STATE(11), 3,
      sym_export_definition,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(43), 5,
      sym_import_definition,
      sym_struct,
      sym_interface,
      sym_impl,
      sym_function,
  [429] = 11,
    ACTIONS(5), 1,
      anon_sym_export,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_interface,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_func,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    STATE(90), 1,
      sym_function_decl,
    STATE(41), 2,
      sym_import_all,
      sym_import_from,
    STATE(11), 3,
      sym_export_definition,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(43), 5,
      sym_import_definition,
      sym_struct,
      sym_interface,
      sym_impl,
      sym_function,
  [470] = 10,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_while,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      sym_identifier,
    STATE(23), 1,
      sym_statement,
    STATE(129), 1,
      sym_variable_specifier,
    ACTIONS(19), 2,
      anon_sym_let,
      anon_sym_const,
    STATE(27), 7,
      sym_block,
      sym_variable,
      sym_if_stmt,
      sym_while_stmt,
      sym_for_stmt,
      sym_return_stmt,
      sym_assignment_stmt,
  [508] = 4,
    STATE(33), 1,
      sym_op,
    ACTIONS(90), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(92), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [531] = 4,
    STATE(33), 1,
      sym_op,
    ACTIONS(94), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(96), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [554] = 4,
    STATE(33), 1,
      sym_op,
    ACTIONS(98), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(100), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [577] = 4,
    STATE(33), 1,
      sym_op,
    ACTIONS(102), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(104), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [600] = 3,
    STATE(33), 1,
      sym_op,
    ACTIONS(106), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [621] = 9,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_interface,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_func,
    STATE(51), 1,
      sym_definition,
    STATE(90), 1,
      sym_function_decl,
    STATE(41), 2,
      sym_import_all,
      sym_import_from,
    STATE(43), 5,
      sym_import_definition,
      sym_struct,
      sym_interface,
      sym_impl,
      sym_function,
  [654] = 2,
    ACTIONS(110), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(112), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [672] = 2,
    ACTIONS(114), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(116), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [690] = 4,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_from,
    STATE(64), 1,
      aux_sym_import_from_repeat1,
    ACTIONS(118), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [709] = 2,
    ACTIONS(124), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(126), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [723] = 2,
    ACTIONS(128), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(130), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [737] = 2,
    ACTIONS(132), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(134), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [751] = 2,
    ACTIONS(136), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(138), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [765] = 2,
    ACTIONS(140), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(142), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [779] = 2,
    ACTIONS(144), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(146), 7,
      anon_sym_let,
      anon_sym_const,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_return,
      sym_identifier,
  [793] = 1,
    ACTIONS(144), 8,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [804] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(2), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [823] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(15), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [842] = 1,
    ACTIONS(136), 8,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [853] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(18), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [872] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(3), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [891] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(14), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [910] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(16), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [929] = 5,
    ACTIONS(152), 1,
      sym_float,
    STATE(17), 1,
      sym_expression,
    ACTIONS(148), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 2,
      sym_boolean_constant,
      sym_binary_op,
  [948] = 1,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [958] = 1,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [968] = 1,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [978] = 1,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [988] = 5,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      anon_sym_func,
    ACTIONS(167), 1,
      sym_identifier,
    STATE(94), 1,
      sym_self_function_decl,
    STATE(42), 3,
      sym_struct_field,
      sym_self_function,
      aux_sym_struct_repeat1,
  [1006] = 1,
    ACTIONS(170), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1016] = 1,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1026] = 1,
    ACTIONS(174), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1036] = 1,
    ACTIONS(176), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1046] = 1,
    ACTIONS(178), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1056] = 1,
    ACTIONS(180), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1066] = 1,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1076] = 5,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    ACTIONS(186), 1,
      anon_sym_func,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(94), 1,
      sym_self_function_decl,
    STATE(42), 3,
      sym_struct_field,
      sym_self_function,
      aux_sym_struct_repeat1,
  [1094] = 1,
    ACTIONS(190), 7,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_import,
      anon_sym_struct,
      anon_sym_interface,
      anon_sym_impl,
      anon_sym_func,
  [1104] = 5,
    ACTIONS(186), 1,
      anon_sym_func,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_self_function_decl,
    STATE(50), 3,
      sym_struct_field,
      sym_self_function,
      aux_sym_struct_repeat1,
  [1122] = 2,
    STATE(31), 1,
      sym_assignment_op,
    ACTIONS(194), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
  [1133] = 2,
    ACTIONS(198), 1,
      sym_float,
    ACTIONS(196), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      sym_integer,
  [1143] = 2,
    ACTIONS(202), 1,
      sym_float,
    ACTIONS(200), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      sym_integer,
  [1153] = 4,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(206), 1,
      anon_sym_func,
    STATE(109), 1,
      sym_self_function_decl,
    STATE(57), 2,
      sym_self_function,
      aux_sym_impl_repeat1,
  [1167] = 4,
    ACTIONS(206), 1,
      anon_sym_func,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(109), 1,
      sym_self_function_decl,
    STATE(58), 2,
      sym_self_function,
      aux_sym_impl_repeat1,
  [1181] = 4,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      anon_sym_func,
    STATE(109), 1,
      sym_self_function_decl,
    STATE(58), 2,
      sym_self_function,
      aux_sym_impl_repeat1,
  [1195] = 3,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      anon_sym_func,
    STATE(61), 2,
      sym_self_function_decl,
      aux_sym_interface_repeat1,
  [1206] = 3,
    ACTIONS(217), 1,
      anon_sym_func,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_self_function_decl,
      aux_sym_interface_repeat1,
  [1217] = 3,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    ACTIONS(223), 1,
      anon_sym_func,
    STATE(61), 2,
      sym_self_function_decl,
      aux_sym_interface_repeat1,
  [1228] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1238] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1248] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_from,
    STATE(68), 1,
      aux_sym_import_from_repeat1,
  [1258] = 2,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    ACTIONS(236), 2,
      anon_sym_func,
      sym_identifier,
  [1266] = 3,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      anon_sym_self,
    ACTIONS(242), 1,
      sym_identifier,
  [1276] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_parameter_list_repeat1,
  [1286] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(249), 1,
      anon_sym_from,
    STATE(68), 1,
      aux_sym_import_from_repeat1,
  [1296] = 1,
    ACTIONS(251), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_func,
  [1302] = 2,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    ACTIONS(255), 2,
      anon_sym_func,
      sym_identifier,
  [1310] = 3,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1320] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
  [1330] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1340] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_parameter_list_repeat1,
  [1350] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1360] = 3,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    ACTIONS(272), 1,
      anon_sym_func,
    ACTIONS(274), 1,
      sym_identifier,
  [1370] = 2,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    ACTIONS(278), 2,
      anon_sym_func,
      sym_identifier,
  [1378] = 2,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    ACTIONS(282), 2,
      anon_sym_func,
      sym_identifier,
  [1386] = 2,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    ACTIONS(286), 2,
      anon_sym_func,
      sym_identifier,
  [1394] = 2,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    ACTIONS(290), 2,
      anon_sym_func,
      sym_identifier,
  [1402] = 2,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    ACTIONS(294), 2,
      anon_sym_func,
      sym_identifier,
  [1410] = 2,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(298), 2,
      anon_sym_func,
      sym_identifier,
  [1418] = 2,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 2,
      anon_sym_func,
      sym_identifier,
  [1426] = 2,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 2,
      anon_sym_func,
      sym_identifier,
  [1434] = 3,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    ACTIONS(302), 1,
      anon_sym_self,
    ACTIONS(304), 1,
      sym_identifier,
  [1444] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_parameter_list_repeat1,
  [1454] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1464] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_parameter_list_repeat1,
  [1474] = 2,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
    STATE(107), 1,
      sym_self_parameter_list,
  [1481] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
  [1488] = 1,
    ACTIONS(276), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1493] = 2,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    ACTIONS(318), 1,
      sym_identifier,
  [1500] = 1,
    ACTIONS(320), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1505] = 2,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
    STATE(65), 1,
      sym_block,
  [1512] = 2,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
    ACTIONS(326), 1,
      sym_identifier,
  [1519] = 1,
    ACTIONS(328), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1524] = 1,
    ACTIONS(280), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1529] = 1,
    ACTIONS(284), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1534] = 1,
    ACTIONS(330), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1539] = 1,
    ACTIONS(288), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1544] = 1,
    ACTIONS(292), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1549] = 1,
    ACTIONS(296), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1554] = 2,
    ACTIONS(332), 1,
      anon_sym_COLON,
    ACTIONS(334), 1,
      anon_sym_EQ,
  [1561] = 1,
    ACTIONS(234), 2,
      anon_sym_RBRACE,
      anon_sym_func,
  [1566] = 2,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
    STATE(112), 1,
      sym_parameter_list,
  [1573] = 1,
    ACTIONS(249), 2,
      anon_sym_COMMA,
      anon_sym_from,
  [1578] = 2,
    ACTIONS(270), 1,
      anon_sym_LBRACE,
    ACTIONS(338), 1,
      sym_identifier,
  [1585] = 1,
    ACTIONS(340), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1590] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_block,
  [1597] = 2,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      sym_self_parameter_list,
  [1604] = 2,
    ACTIONS(344), 1,
      anon_sym_RPAREN,
    ACTIONS(346), 1,
      sym_identifier,
  [1611] = 2,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    ACTIONS(350), 1,
      sym_identifier,
  [1618] = 1,
    ACTIONS(352), 1,
      sym_identifier,
  [1622] = 1,
    ACTIONS(354), 1,
      sym_identifier,
  [1626] = 1,
    ACTIONS(356), 1,
      sym_identifier,
  [1630] = 1,
    ACTIONS(358), 1,
      sym_identifier,
  [1634] = 1,
    ACTIONS(360), 1,
      sym_identifier,
  [1638] = 1,
    ACTIONS(362), 1,
      sym_identifier,
  [1642] = 1,
    ACTIONS(364), 1,
      sym_identifier,
  [1646] = 1,
    ACTIONS(366), 1,
      sym_identifier,
  [1650] = 1,
    ACTIONS(368), 1,
      anon_sym_EQ,
  [1654] = 1,
    ACTIONS(370), 1,
      anon_sym_LBRACE,
  [1658] = 1,
    ACTIONS(372), 1,
      sym_identifier,
  [1662] = 1,
    ACTIONS(374), 1,
      sym_identifier,
  [1666] = 1,
    ACTIONS(376), 1,
      anon_sym_COLON,
  [1670] = 1,
    ACTIONS(378), 1,
      anon_sym_COMMA,
  [1674] = 1,
    ACTIONS(380), 1,
      anon_sym_LBRACE,
  [1678] = 1,
    ACTIONS(382), 1,
      anon_sym_on,
  [1682] = 1,
    ACTIONS(384), 1,
      sym_identifier,
  [1686] = 1,
    ACTIONS(386), 1,
      sym_identifier,
  [1690] = 1,
    ACTIONS(388), 1,
      anon_sym_COLON,
  [1694] = 1,
    ACTIONS(390), 1,
      sym_identifier,
  [1698] = 1,
    ACTIONS(392), 1,
      anon_sym_in,
  [1702] = 1,
    ACTIONS(394), 1,
      sym_identifier,
  [1706] = 1,
    ACTIONS(396), 1,
      anon_sym_COLON,
  [1710] = 1,
    ACTIONS(398), 1,
      anon_sym_LBRACE,
  [1714] = 1,
    ACTIONS(400), 1,
      sym_identifier,
  [1718] = 1,
    ACTIONS(402), 1,
      sym_identifier,
  [1722] = 1,
    ACTIONS(404), 1,
      sym_identifier,
  [1726] = 1,
    ACTIONS(406), 1,
      anon_sym_COMMA,
  [1730] = 1,
    ACTIONS(408), 1,
      sym_identifier,
  [1734] = 1,
    ACTIONS(410), 1,
      ts_builtin_sym_end,
  [1738] = 1,
    ACTIONS(412), 1,
      anon_sym_COLON,
  [1742] = 1,
    ACTIONS(414), 1,
      sym_identifier,
  [1746] = 1,
    ACTIONS(416), 1,
      sym_identifier,
  [1750] = 1,
    ACTIONS(418), 1,
      anon_sym_COLON,
  [1754] = 1,
    ACTIONS(420), 1,
      anon_sym_LBRACE,
  [1758] = 1,
    ACTIONS(422), 1,
      sym_identifier,
  [1762] = 1,
    ACTIONS(424), 1,
      anon_sym_COMMA,
  [1766] = 1,
    ACTIONS(426), 1,
      sym_identifier,
  [1770] = 1,
    ACTIONS(428), 1,
      sym_identifier,
  [1774] = 1,
    ACTIONS(430), 1,
      anon_sym_COLON,
  [1778] = 1,
    ACTIONS(432), 1,
      anon_sym_COLON,
  [1782] = 1,
    ACTIONS(434), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 262,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 388,
  [SMALL_STATE(12)] = 429,
  [SMALL_STATE(13)] = 470,
  [SMALL_STATE(14)] = 508,
  [SMALL_STATE(15)] = 531,
  [SMALL_STATE(16)] = 554,
  [SMALL_STATE(17)] = 577,
  [SMALL_STATE(18)] = 600,
  [SMALL_STATE(19)] = 621,
  [SMALL_STATE(20)] = 654,
  [SMALL_STATE(21)] = 672,
  [SMALL_STATE(22)] = 690,
  [SMALL_STATE(23)] = 709,
  [SMALL_STATE(24)] = 723,
  [SMALL_STATE(25)] = 737,
  [SMALL_STATE(26)] = 751,
  [SMALL_STATE(27)] = 765,
  [SMALL_STATE(28)] = 779,
  [SMALL_STATE(29)] = 793,
  [SMALL_STATE(30)] = 804,
  [SMALL_STATE(31)] = 823,
  [SMALL_STATE(32)] = 842,
  [SMALL_STATE(33)] = 853,
  [SMALL_STATE(34)] = 872,
  [SMALL_STATE(35)] = 891,
  [SMALL_STATE(36)] = 910,
  [SMALL_STATE(37)] = 929,
  [SMALL_STATE(38)] = 948,
  [SMALL_STATE(39)] = 958,
  [SMALL_STATE(40)] = 968,
  [SMALL_STATE(41)] = 978,
  [SMALL_STATE(42)] = 988,
  [SMALL_STATE(43)] = 1006,
  [SMALL_STATE(44)] = 1016,
  [SMALL_STATE(45)] = 1026,
  [SMALL_STATE(46)] = 1036,
  [SMALL_STATE(47)] = 1046,
  [SMALL_STATE(48)] = 1056,
  [SMALL_STATE(49)] = 1066,
  [SMALL_STATE(50)] = 1076,
  [SMALL_STATE(51)] = 1094,
  [SMALL_STATE(52)] = 1104,
  [SMALL_STATE(53)] = 1122,
  [SMALL_STATE(54)] = 1133,
  [SMALL_STATE(55)] = 1143,
  [SMALL_STATE(56)] = 1153,
  [SMALL_STATE(57)] = 1167,
  [SMALL_STATE(58)] = 1181,
  [SMALL_STATE(59)] = 1195,
  [SMALL_STATE(60)] = 1206,
  [SMALL_STATE(61)] = 1217,
  [SMALL_STATE(62)] = 1228,
  [SMALL_STATE(63)] = 1238,
  [SMALL_STATE(64)] = 1248,
  [SMALL_STATE(65)] = 1258,
  [SMALL_STATE(66)] = 1266,
  [SMALL_STATE(67)] = 1276,
  [SMALL_STATE(68)] = 1286,
  [SMALL_STATE(69)] = 1296,
  [SMALL_STATE(70)] = 1302,
  [SMALL_STATE(71)] = 1310,
  [SMALL_STATE(72)] = 1320,
  [SMALL_STATE(73)] = 1330,
  [SMALL_STATE(74)] = 1340,
  [SMALL_STATE(75)] = 1350,
  [SMALL_STATE(76)] = 1360,
  [SMALL_STATE(77)] = 1370,
  [SMALL_STATE(78)] = 1378,
  [SMALL_STATE(79)] = 1386,
  [SMALL_STATE(80)] = 1394,
  [SMALL_STATE(81)] = 1402,
  [SMALL_STATE(82)] = 1410,
  [SMALL_STATE(83)] = 1418,
  [SMALL_STATE(84)] = 1426,
  [SMALL_STATE(85)] = 1434,
  [SMALL_STATE(86)] = 1444,
  [SMALL_STATE(87)] = 1454,
  [SMALL_STATE(88)] = 1464,
  [SMALL_STATE(89)] = 1474,
  [SMALL_STATE(90)] = 1481,
  [SMALL_STATE(91)] = 1488,
  [SMALL_STATE(92)] = 1493,
  [SMALL_STATE(93)] = 1500,
  [SMALL_STATE(94)] = 1505,
  [SMALL_STATE(95)] = 1512,
  [SMALL_STATE(96)] = 1519,
  [SMALL_STATE(97)] = 1524,
  [SMALL_STATE(98)] = 1529,
  [SMALL_STATE(99)] = 1534,
  [SMALL_STATE(100)] = 1539,
  [SMALL_STATE(101)] = 1544,
  [SMALL_STATE(102)] = 1549,
  [SMALL_STATE(103)] = 1554,
  [SMALL_STATE(104)] = 1561,
  [SMALL_STATE(105)] = 1566,
  [SMALL_STATE(106)] = 1573,
  [SMALL_STATE(107)] = 1578,
  [SMALL_STATE(108)] = 1585,
  [SMALL_STATE(109)] = 1590,
  [SMALL_STATE(110)] = 1597,
  [SMALL_STATE(111)] = 1604,
  [SMALL_STATE(112)] = 1611,
  [SMALL_STATE(113)] = 1618,
  [SMALL_STATE(114)] = 1622,
  [SMALL_STATE(115)] = 1626,
  [SMALL_STATE(116)] = 1630,
  [SMALL_STATE(117)] = 1634,
  [SMALL_STATE(118)] = 1638,
  [SMALL_STATE(119)] = 1642,
  [SMALL_STATE(120)] = 1646,
  [SMALL_STATE(121)] = 1650,
  [SMALL_STATE(122)] = 1654,
  [SMALL_STATE(123)] = 1658,
  [SMALL_STATE(124)] = 1662,
  [SMALL_STATE(125)] = 1666,
  [SMALL_STATE(126)] = 1670,
  [SMALL_STATE(127)] = 1674,
  [SMALL_STATE(128)] = 1678,
  [SMALL_STATE(129)] = 1682,
  [SMALL_STATE(130)] = 1686,
  [SMALL_STATE(131)] = 1690,
  [SMALL_STATE(132)] = 1694,
  [SMALL_STATE(133)] = 1698,
  [SMALL_STATE(134)] = 1702,
  [SMALL_STATE(135)] = 1706,
  [SMALL_STATE(136)] = 1710,
  [SMALL_STATE(137)] = 1714,
  [SMALL_STATE(138)] = 1718,
  [SMALL_STATE(139)] = 1722,
  [SMALL_STATE(140)] = 1726,
  [SMALL_STATE(141)] = 1730,
  [SMALL_STATE(142)] = 1734,
  [SMALL_STATE(143)] = 1738,
  [SMALL_STATE(144)] = 1742,
  [SMALL_STATE(145)] = 1746,
  [SMALL_STATE(146)] = 1750,
  [SMALL_STATE(147)] = 1754,
  [SMALL_STATE(148)] = 1758,
  [SMALL_STATE(149)] = 1762,
  [SMALL_STATE(150)] = 1766,
  [SMALL_STATE(151)] = 1770,
  [SMALL_STATE(152)] = 1774,
  [SMALL_STATE(153)] = 1778,
  [SMALL_STATE(154)] = 1782,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(138),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(134),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(141),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_stmt, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_stmt, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 6, 0, 5),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 6, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_constant, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_constant, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_all, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_stmt, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_stmt, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stmt, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_stmt, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_stmt, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_from, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 5, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_definition, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl, 7, 0, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_from, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl, 6, 0, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 4, 0, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_definition, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_op, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_op, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_op, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interface_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interface_repeat1, 2, 0, 0), SHIFT_REPEAT(148),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_function, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_function, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_from_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_from_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_function_decl, 4, 0, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 4),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_field, 4, 0, 4),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 7), SHIFT_REPEAT(120),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 7),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_function_decl, 3, 0, 1),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_function_decl, 3, 0, 1),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 4, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 4, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 5, 0, 5),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 5, 0, 5),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 6, 0, 6),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 6, 0, 6),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 7, 0, 8),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 7, 0, 8),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_parameter_list, 8, 0, 9),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_parameter_list, 8, 0, 9),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5, 0, 5),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 6, 0, 6),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 4, 0, 5),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 3, 0, 1),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_specifier, 1, 0, 0),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [410] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 4, 0, 2),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_emble(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "emble",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
